# Generated by Django 3.2.4 on 2021-06-20 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kppshka', '0002_auto_20210605_1126'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='comment_approved',
            field=models.BooleanField(default=True, verbose_name='Камент одобрен'),
        ),
    ]
